spring.application.name=techassets
spring.datasource.url=jdbc:postgresql://localhost:5432/techassets
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true